### ISSUE TITLE
image resize per screen device error

### ISSUE THREAD

**Issue by MohammadTaseenKhan** [jeremyckahn/chitchatter#289] opened 2024-05-05 18:45 UTC
### Summary
Sharing images is the vital part of a secure chatting platform but in terms of flexibility we are facing problems like after uploading an image in smartphone the image does not perfectly fit with the device screen size and frame that holds the image as a layout around it in terms of responsiveness although it works fine on desktop screen.

### Details

> desktop view: 
![Screenshot 2024-05-05 192642](https://github.com/jeremyckahn/chitchatter/assets/85288261/0ec07f5b-6f31-4be4-9d03-30de9d465dec)

> phone view:
![c7ec74cd-8db0-48ff-ba3b-63821a73c020](https://github.com/jeremyckahn/chitchatter/assets/85288261/3af9e5a1-6157-482a-991f-a81fdb63ae68)

### Impact
It even leads to major problems such as the mobile screen not fitting properly due to the image being too wide to view the screen.

**Comment by jeremyckahn** [comment] 2024-05-05 22:44
Thanks for reporting, @MohammadTaseenKhan. This would be a good first issue for someone to pick up, so I've added the appropriate label for that.

**Comment by brentonv** [comment] 2024-05-07 11:32
@jeremyckahn this is essentially what I was explaining in #280 

> Large images in the chat block require much scrolling and it's difficult to view

**Comment by jeremyckahn** [comment] 2024-05-07 23:47
> this is essentially what I was explaining in #280

Ah, I see! In that case, I'll close this as a duplicate of #280.

Thanks for the additional information and screenshots, @MohammadTaseenKhan.

**Closed by jeremyckahn** 2024-05-07 23:47 UTC
Labels: bug, good first issue
