### ISSUE TITLE
WebSocket connection to 'wss://tracker.openwebtorrent.com/' failed: 

### ISSUE THREAD

**Issue by CarryOnHxy** [jeremyckahn/chitchatter#126] opened 2023-06-29 07:06 UTC
![image](https://github.com/jeremyckahn/chitchatter/assets/41328326/4f5d0931-f15a-4bbe-8b23-a3d26966f126)

Accessing link: https://chitchatter.im/

After accessing the main page to start a public or private room and type message,  my friend who get the shared link couldn't receive my message and the errors above i found in the console of Chrome.

**Comment by jeremyckahn** [comment] 2023-06-29 14:04
Hi @CarryOnHxy, thanks for reporting this. I just tested https://chitchatter.im/ and I am able to connect peers once I disable my browsers' ad blockers. [This is a known issue](https://github.com/jeremyckahn/chitchatter#issues-specific-to-browsers-with-ad-blocking-extensions) that unfortunately can't be worked around at an application level.

Could you please try disabling your adblocker for https://chitchatter.im/, seeing if that works for you, and let me know?

**Comment by CarryOnHxy** [comment] 2023-06-30 13:34
> Hi @CarryOnHxy, thanks for reporting this. I just tested https://chitchatter.im/ and I am able to connect peers once I disable my browsers' ad blockers. [This is a known issue](https://github.com/jeremyckahn/chitchatter#issues-specific-to-browsers-with-ad-blocking-extensions) that unfortunately can't be worked around at an application level.
> 
> Could you please try disabling your adblocker for https://chitchatter.im/, seeing if that works for you, and let me know?

Yes, I disabled my adblocker, but the following new errors appeared.
![image](https://github.com/jeremyckahn/chitchatter/assets/41328326/ccce2bd4-ea5c-41df-a898-189b7e62e698)
WebSocket connection to 'wss://tracker.files.fm:7073/announce' failed:

**Comment by jeremyckahn** [comment] 2023-06-30 14:18
Thanks for following up about this @CarryOnHxy, and for the screenshot. I'm not able to reproduce this issue, and Chitchatter peers are able to connect for me.

I can see from the network indicator in the top right of the screenshot that you have "No network connection," but you at least had a "Partial network connection" in your previous screenshot. Did something about the network you're on change between those two screenshots?

"No network connection" means that you're not able to connect to any WebTorrent pairing server, so you won't be able to connect to other peers. You might want to try changing your location to be on a different network, because something seems to be blocking your connection.

> WebSocket connection to 'wss://tracker.files.fm:7073/announce' failed:

This will happen from time to time, but Chitchatter (via [Trystero](https://github.com/dmotz/trystero)) uses a redundancy strategy to use multiple trackers to connect in case one is unavailable. However, something doesn't seem to be working correctly in this case. According to [Trystero's docs](https://github.com/dmotz/trystero#joinroomconfig-namespace), `trackerRedundancy` can be increased to 3 from the current default of 2. I'll make that change to see if it helps here.

**Comment by jeremyckahn** [comment] 2023-06-30 14:28
@CarryOnHxy https://chitchatter.im/ has been updated to use more tracker redundancy for better reliability. Can you give it another try and let me know what happens? If you can, please use the same network you did when had the "Partial network connection" in your first screenshot.

**Comment by CarryOnHxy** [comment] 2023-06-30 14:47
> @CarryOnHxy https://chitchatter.im/ has been updated to use more tracker redundancy for better reliability. Can you give it another try and let me know what happens? If you can, please use the same network you did when had the "Partial network connection" in your first screenshot.

Thank you very much for your seriousness and responsibility. Surely the first snapshot and second snapshot are on the different network, and the first one i took at company, though i can reproduce it but sorry for two days later. Have a good one!

**Comment by CarryOnHxy** [comment] 2023-07-03 09:26
> @CarryOnHxy https://chitchatter.im/ has been updated to use more tracker redundancy for better reliability. Can you give it another try and let me know what happens? If you can, please use the same network you did when had the "Partial network connection" in your first screenshot.

![image](https://github.com/jeremyckahn/chitchatter/assets/41328326/3d3da6b7-d09c-403a-b50e-c19777aad4bf)

Hey, i tried to use chitchatter with the network you saw in first snapshot without adblocker, it workd fortunately. I opened the same link with different web browser as chrome and edge, the message from each other could be displayed on chitchatter, but the following errors showed as usual: 

WebSocket connection to 'wss://tracker.files.fm:7073/announce' failed:
WebSocket connection to 'wss://tracker.openwebtorrent.com/' failed: 

And then i used Safari to open the link, but it didn't work and received the message from chrome or edge, no reaction.

**Comment by jeremyckahn** [comment] 2023-07-03 14:38
Awesome, I'm glad to see that disabling the adblocker helped! Thanks for letting me know. It would be worth mentioning that in the app so that others don't run into this. I'll file an issue to get that done.

> the message from each other could be displayed on chitchatter, but the following errors showed as usual:
>
> WebSocket connection to 'wss://tracker.files.fm:7073/announce' failed:
> WebSocket connection to 'wss://tracker.openwebtorrent.com/' failed:

That's not surprising. But it looks like https://github.com/jeremyckahn/chitchatter/commit/83e9f7dbddfd2051cb8f50dd570aca8085bdf2db at least connected you to one WebTorrent server, which is all that's needed to connect peers!

> And then i used Safari to open the link, but it didn't work and received the message from chrome or edge, no reaction.

So you're saying that Chrome and Edge can connect to each other, but Safari (I'm assuming the desktop version) can't connect to any other browser? Does Safari-to-Safari work (with Chitchatter loaded in two tabs)?

**Comment by CarryOnHxy** [comment] 2023-07-04 01:29
> Awesome, I'm glad to see that disabling the adblocker helped! Thanks for letting me know. It would be worth mentioning that in the app so that others don't run into this. I'll file an issue to get that done.
> 
> > the message from each other could be displayed on chitchatter, but the following errors showed as usual:
> > WebSocket connection to 'wss://tracker.files.fm:7073/announce' failed:
> > WebSocket connection to 'wss://tracker.openwebtorrent.com/' failed:
> 
> That's not surprising. But it looks like [83e9f7d](https://github.com/jeremyckahn/chitchatter/commit/83e9f7dbddfd2051cb8f50dd570aca8085bdf2db) at least connected you to one WebTorrent server, which is all that's needed to connect peers!
> 
> > And then i used Safari to open the link, but it didn't work and received the message from chrome or edge, no reaction.
> 
> So you're saying that Chrome and Edge can connect to each other, but Safari (I'm assuming the desktop version) can't connect to any other browser? Does Safari-to-Safari work (with Chitchatter loaded in two tabs)?

I used Safari on iphone and i don't have methods like [vconsole](https://github.com/Tencent/vConsole) or something to debug that.

**Comment by jeremyckahn** [comment] 2023-07-04 17:55
Thanks for clarifying that you're using mobile Safari @CarryOnHxy. Chitchatter supports iOS, but I've found that it has poorer reliability on that platform compared to desktops. My best guess is WebRTC bugs in the browser itself are causing this, as Safari's WebRTC support (which Chitchatter relies on) [is known to be quite poor](https://news.ycombinator.com/item?id=27031393).

I'm currently able to connect Chitchatter peers across desktop Firefox and mobile Safari, so I'm thinking that the failure to connect is due to some inexplicable Safari WebRTC instability. There's a chance it may work in iOS Safari if you try again another time (so long as iOS is connected to WiFi) and you open Chitchatter in Safari directly, rather than in the WebView you've got pictured here (sometimes that makes a difference).

At the moment I'm not sure that anything can be done to Chitchatter to improve this issue, so I'm going to close it for now. Feel free to leave more comments and continue the conversation. We can reopen this if it turns out there's anything actionable that can be done to Chitchatter to improve connections for you.

**Closed by jeremyckahn** 2023-07-04 17:55 UTC
