### ISSUE TITLE
Bug: File upload button still shows cancel even after file has already been 100% uploaded

### ISSUE THREAD

**Issue by dillfrescott** [jeremyckahn/chitchatter#104] opened 2023-03-11 18:15 UTC
![Screenshot 2023-03-11 131531](https://user-images.githubusercontent.com/56714680/224504985-b5997c29-d0bb-4f45-8790-d1617298c068.png)

**Comment by dillfrescott** [comment] 2023-03-11 18:15
In that photo, the picture has already been posted to chat

**Comment by jeremyckahn** [comment] 2023-03-12 22:43
Hi @dillfrescott, thanks for reporting this. This is the intended behavior of the file sharing the functionality. The idea is that a file offerer can keep the file up for offer as long as they'd like for others in the room to download (as there may be many people in the room). Is there something else you have in mind for how this might work?

**Comment by dillfrescott** [comment] 2023-03-12 22:56
Hmm. What you say makes a lot of sense. I wasn't thinking of it that way. I think it might be best to keep the current functionality then.

**Comment by jeremyckahn** [comment] 2023-03-12 23:16
Sounds good. I'm open to changing this to be more straightforward, so please comment if any ideas for changing the UI come to you later. I'll close this issue for now.

**Closed by jeremyckahn** 2023-03-12 23:16 UTC
